/**
 * In-memory fixture store backing the mock Rho API.
 *
 * One simulated ledger per sample company, generated by
 * scripts/generate-rho-fixtures.ts and committed, so every machine and CI see
 * identical data. Treat it as read-only.
 */

import type {
  RhoAccount,
  RhoCard,
  RhoInvoice,
  RhoInvoicingCustomer,
  RhoTransaction,
} from "../types";

import northstarAccounts from "../fixtures/northstar-labs/accounts.json";
import northstarCards from "../fixtures/northstar-labs/cards.json";
import northstarCustomers from "../fixtures/northstar-labs/customers.json";
import northstarInvoices from "../fixtures/northstar-labs/invoices.json";
import northstarMeta from "../fixtures/northstar-labs/meta.json";
import northstarTransactions from "../fixtures/northstar-labs/transactions.json";

import acmeAccounts from "../fixtures/acme-ai/accounts.json";
import acmeCards from "../fixtures/acme-ai/cards.json";
import acmeCustomers from "../fixtures/acme-ai/customers.json";
import acmeInvoices from "../fixtures/acme-ai/invoices.json";
import acmeMeta from "../fixtures/acme-ai/meta.json";
import acmeTransactions from "../fixtures/acme-ai/transactions.json";

import quiverleafAccounts from "../fixtures/quiverleaf-ai/accounts.json";
import quiverleafCards from "../fixtures/quiverleaf-ai/cards.json";
import quiverleafCustomers from "../fixtures/quiverleaf-ai/customers.json";
import quiverleafInvoices from "../fixtures/quiverleaf-ai/invoices.json";
import quiverleafMeta from "../fixtures/quiverleaf-ai/meta.json";
import quiverleafTransactions from "../fixtures/quiverleaf-ai/transactions.json";

import lanternfishAccounts from "../fixtures/lanternfish-analytics/accounts.json";
import lanternfishCards from "../fixtures/lanternfish-analytics/cards.json";
import lanternfishCustomers from "../fixtures/lanternfish-analytics/customers.json";
import lanternfishInvoices from "../fixtures/lanternfish-analytics/invoices.json";
import lanternfishMeta from "../fixtures/lanternfish-analytics/meta.json";
import lanternfishTransactions from "../fixtures/lanternfish-analytics/transactions.json";

export interface FixtureMeta {
  generator: string;
  seed: number;
  /** The fixture's "today". Compute metrics relative to this, not the clock. */
  anchor: string;
  company: string;
  slug: string;
  short_name: string;
  description: string;
  /** Not a secret: it only opens this simulated ledger on the mock API. */
  mock_token: string;
  /**
   * The customers are real businesses used for illustration, so research on them
   * runs live. The ledger is still synthetic; no relationship is implied.
   */
  real_customers?: boolean;
  /** Connected only by pasting its token; never listed as a sample company. */
  token_only?: boolean;
  period: { first_month: string; last_month: string };
  counts: Record<string, number>;
  opening_balances: Record<string, number>;
}

/** One simulated company's complete Rho ledger. */
export interface MockCompany {
  meta: FixtureMeta;
  accounts: RhoAccount[];
  transactions: RhoTransaction[];
  cards: RhoCard[];
  customers: RhoInvoicingCustomer[];
  invoices: RhoInvoice[];
}

const company = (data: {
  meta: unknown;
  accounts: unknown;
  transactions: unknown;
  cards: unknown;
  customers: unknown;
  invoices: unknown;
}): MockCompany => data as MockCompany;

/** Headline company first: it is the one the demo opens. */
export const mockCompanies: readonly MockCompany[] = [
  company({
    meta: acmeMeta,
    accounts: acmeAccounts,
    transactions: acmeTransactions,
    cards: acmeCards,
    customers: acmeCustomers,
    invoices: acmeInvoices,
  }),
  company({
    meta: northstarMeta,
    accounts: northstarAccounts,
    transactions: northstarTransactions,
    cards: northstarCards,
    customers: northstarCustomers,
    invoices: northstarInvoices,
  }),
  company({
    meta: quiverleafMeta,
    accounts: quiverleafAccounts,
    transactions: quiverleafTransactions,
    cards: quiverleafCards,
    customers: quiverleafCustomers,
    invoices: quiverleafInvoices,
  }),
  company({
    meta: lanternfishMeta,
    accounts: lanternfishAccounts,
    transactions: lanternfishTransactions,
    cards: lanternfishCards,
    customers: lanternfishCustomers,
    invoices: lanternfishInvoices,
  }),
];

/** Offered as one-click sample companies. Token-only companies are connected by token. */
export const listedCompanies: readonly MockCompany[] = mockCompanies.filter((c) => !c.meta.token_only);

/** Each token opens exactly one company's ledger, like a real Rho token. */
export function companyForToken(token: string): MockCompany | null {
  return mockCompanies.find((c) => c.meta.mock_token === token) ?? null;
}

export function companyBySlug(slug: string): MockCompany | null {
  return mockCompanies.find((c) => c.meta.slug === slug) ?? null;
}

/**
 * The sample company a mock connection was made from. Connections store a label
 * derived from the account names ("Acme AI"), or the legal name when seeded.
 */
export function companyByName(name: string): MockCompany | null {
  const wanted = name.replace(/\s*\(mock\)\s*$/i, "").trim().toLowerCase();
  return mockCompanies.find((c) =>
    c.meta.short_name.toLowerCase() === wanted || c.meta.company.toLowerCase() === wanted) ?? null;
}

/** Matches `?foo=a&foo=b`; an empty filter list means "no filter". */
export function matchesAny(
  values: string[],
  value: string | null | undefined,
): boolean {
  if (values.length === 0) return true;
  return value != null && values.includes(value);
}

export function withinRange(
  value: string | null,
  afterInclusive: string | null,
  beforeExclusive: string | null,
): boolean {
  if (!afterInclusive && !beforeExclusive) return true;
  if (value == null) return false;
  const t = Date.parse(value);
  if (afterInclusive && t < Date.parse(afterInclusive)) return false;
  if (beforeExclusive && t >= Date.parse(beforeExclusive)) return false;
  return true;
}
