/**
 * In-memory fixture store backing the mock Rho API.
 *
 * The JSON is generated by scripts/generate-rho-fixtures.ts and committed, so
 * the dataset is identical on every machine and in CI. Treat it as read-only.
 */

import type {
  RhoAccount,
  RhoCard,
  RhoInvoice,
  RhoInvoicingCustomer,
  RhoTransaction,
} from "../types";

import accountsJson from "../fixtures/accounts.json";
import cardsJson from "../fixtures/cards.json";
import customersJson from "../fixtures/customers.json";
import invoicesJson from "../fixtures/invoices.json";
import metaJson from "../fixtures/meta.json";
import transactionsJson from "../fixtures/transactions.json";

export const accounts = accountsJson as unknown as RhoAccount[];
export const transactions = transactionsJson as unknown as RhoTransaction[];
export const cards = cardsJson as unknown as RhoCard[];
export const customers = customersJson as unknown as RhoInvoicingCustomer[];
export const invoices = invoicesJson as unknown as RhoInvoice[];

export interface FixtureMeta {
  generator: string;
  seed: number;
  /** The fixture's "today". Compute metrics relative to this, not the clock. */
  anchor: string;
  company: string;
  period: { first_month: string; last_month: string };
  counts: Record<string, number>;
  opening_balances: Record<string, number>;
}
export const meta = metaJson as FixtureMeta;

/** Matches `?foo=a&foo=b`; an empty filter list means "no filter". */
export function matchesAny(
  values: string[],
  value: string | null | undefined,
): boolean {
  if (values.length === 0) return true;
  return value != null && values.includes(value);
}

export function withinRange(
  value: string | null,
  afterInclusive: string | null,
  beforeExclusive: string | null,
): boolean {
  if (!afterInclusive && !beforeExclusive) return true;
  if (value == null) return false;
  const t = Date.parse(value);
  if (afterInclusive && t < Date.parse(afterInclusive)) return false;
  if (beforeExclusive && t >= Date.parse(beforeExclusive)) return false;
  return true;
}
